apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethlogger.fullname" . }}
  labels:
    {{- include "ethlogger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ethlogger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ethlogger.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ethlogger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/abis
              name: abis
          env:
            - name: COLLECT_BLOCKS
              value: {{ .Values.collectBlocks | quote }}
            - name: COLLECT_NODE_METRICS
              value: {{ .Values.collectNodeMetrics | quote }}
            - name: COLLECT_NODE_INFO
              value: {{ .Values.collectNodeInfo | quote }}
            - name: COLLECT_PENDING_TX
              value: {{ .Values.collectPendingTransactions | quote }}
            - name: COLLECT_PEER_INFO
              value: {{ .Values.collectPeerInfo | quote }}
            - name: COLLECT_INTERNAL_METRICS
              value: {{ .Values.collectInternalMetrics | quote }}
            - name: SPLUNK_HEC_URL
              value: {{ .Values.splunkHecURL | quote  }}
            - name: SPLUNK_HEC_TOKEN
              value: {{ .Values.splunkToken | quote  }}
            - name: SPLUNK_HEC_REJECT_INVALID_CERTS
              value: {{ .Values.splunkHecRejectInvalidCerts | quote }}
            {{ if .Values.splunkEventsIndex  }}
            - name: SPLUNK_EVENTS_INDEX
              value: {{ .Values.splunkEventsIndex | quote }}
            {{ end }}
            {{ if .Values.splunkMetricsIndex  }}
            - name: SPLUNK_METRICS_INDEX
              value: {{ .Values.splunkMetricsIndex | quote  }}
            {{ end }}
            {{ if .Values.splunkInternalIndex  }}
            - name: SPLUNK_INTERNAL_INDEX
              value: {{ .Values.splunkInternalIndex | quote }}
            {{ end }}
            {{ if .Values.splunkEventsHecToken  }}
            - name: SPLUNK_EVENTS_HEC_TOKEN
              value: {{ .Values.splunkEventsHecToken | quote }}
            {{ end }}
            {{ if .Values.splunkMetricsHecToken  }}
            - name: SPLUNK_METRICS_HEC_TOKEN
              value: {{ .Values.splunkMetricsHecToken | quote }}
            {{ end }}
            {{ if .Values.splunkInternalHecToken  }}
            - name: SPLUNK_INTERNAL_HEC_TOKEN
              value: {{ .Values.splunkInternalHecToken | quote }}
            {{ end }}
            - name: ETH_RPC_URL
              value: {{ .Values.ethRpcUrl| quote  }}
            - name: ETH_REJECT_INVALID_CERTS
              value: {{ .Values.ethRejectInvalidCerts | quote }}
            - name: ABI_DIR
              value: "/var/abis"
            - name: START_AT_BLOCK
              value: {{ .Values.startAtBlock | quote  }}
            - name: REJECT_INVALID_CERTS
              value: {{ .Values.rejectInvalidCerts | quote }}
            - name: NETWORK_NAME
              value: {{ .Values.networkName | quote  }}
            - name: CHAIN_NAME
              value: {{ .Values.chainName| quote  }}
          {{- with .Values.env }}
            {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - ethlogger
                - --health-check
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: abis
          configMap:
              name: abis
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
